# Use "zengxs/gitlab:latest" image for ARM64-Macbooks with M-Chip
# Use "gitlab/gitlab-ce" image for AMD64-Intel-Chips
version: '3.7'

services:
  gitlab:
    #image: zengxs/gitlab:latest
    image: gitlab/gitlab-ce
    container_name: gitlab
    ports:
      - "8080:80"
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
    restart: always

  terraform:
    image: hashicorp/terraform:0.12.21
    container_name: terraform
    volumes:
      - ./infra:/infra
    working_dir: /infra
    command: ["terraform", "init"]
    restart: 'no'  # Verhindert Neustart-Schleife

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config: